// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3._1.Data;

namespace _3._1.Migrations
{
    [DbContext(typeof(_3_1Context))]
    [Migration("20201106190154_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_3._1.Models.AccountPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AccountPlan");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "2",
                            Number = 3,
                            Type = "3"
                        },
                        new
                        {
                            ID = 2,
                            Name = "3",
                            Number = 2,
                            Type = "4"
                        },
                        new
                        {
                            ID = 3,
                            Name = "4",
                            Number = 4,
                            Type = "5"
                        },
                        new
                        {
                            ID = 4,
                            Name = "5",
                            Number = 5,
                            Type = "6"
                        },
                        new
                        {
                            ID = 5,
                            Name = "6",
                            Number = 6,
                            Type = "7"
                        },
                        new
                        {
                            ID = 6,
                            Name = "7",
                            Number = 7,
                            Type = "8"
                        },
                        new
                        {
                            ID = 7,
                            Name = "8",
                            Number = 8,
                            Type = "9"
                        });
                });

            modelBuilder.Entity("_3._1.Models.Deal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Agreement")
                        .HasColumnType("real");

                    b.Property<float>("Commission")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Tiker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int");

                    b.Property<int>("Trader")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Deal");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Agreement = 2f,
                            Commission = 1f,
                            Date = new DateTime(2020, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 2,
                            Order = 2,
                            Price = 2f,
                            Quantity = 3,
                            Tiker = "1",
                            TotalCost = 1,
                            Trader = 2
                        },
                        new
                        {
                            ID = 2,
                            Agreement = 1f,
                            Commission = 2f,
                            Date = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 1,
                            Order = 1,
                            Price = 1f,
                            Quantity = 1,
                            Tiker = "3",
                            TotalCost = 2,
                            Trader = 1
                        },
                        new
                        {
                            ID = 3,
                            Agreement = 22f,
                            Commission = 14f,
                            Date = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 24,
                            Order = 23,
                            Price = 25f,
                            Quantity = 30,
                            Tiker = "111",
                            TotalCost = 17,
                            Trader = 26
                        },
                        new
                        {
                            ID = 4,
                            Agreement = 22f,
                            Commission = 101f,
                            Date = new DateTime(2020, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 25,
                            Order = 24,
                            Price = 28f,
                            Quantity = 7,
                            Tiker = "13",
                            TotalCost = 19,
                            Trader = 200
                        },
                        new
                        {
                            ID = 5,
                            Agreement = 202f,
                            Commission = 111f,
                            Date = new DateTime(2020, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 205,
                            Order = 204,
                            Price = 208f,
                            Quantity = 307,
                            Tiker = "103",
                            TotalCost = 109,
                            Trader = 200
                        },
                        new
                        {
                            ID = 6,
                            Agreement = 63f,
                            Commission = 777f,
                            Date = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 231,
                            Order = 262,
                            Price = 267f,
                            Quantity = 27,
                            Tiker = "163",
                            TotalCost = 2222,
                            Trader = 666
                        },
                        new
                        {
                            ID = 7,
                            Agreement = 777f,
                            Commission = 666f,
                            Date = new DateTime(2020, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = 777,
                            Order = 666,
                            Price = 777f,
                            Quantity = 666,
                            Tiker = "7676",
                            TotalCost = 666,
                            Trader = 777
                        });
                });

            modelBuilder.Entity("_3._1.Models.Operation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealID")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<float>("SaldoInput")
                        .HasColumnType("real");

                    b.Property<float>("SaldoOutput")
                        .HasColumnType("real");

                    b.Property<int>("SubAccountID")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Operation");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Data = new DateTime(2020, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 1,
                            Number = 2,
                            SaldoInput = 1f,
                            SaldoOutput = 2f,
                            SubAccountID = 1,
                            Sum = 2f,
                            Type = "3"
                        },
                        new
                        {
                            ID = 2,
                            Data = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 2,
                            Number = 1,
                            SaldoInput = 3f,
                            SaldoOutput = 1f,
                            SubAccountID = 2,
                            Sum = 1f,
                            Type = "1"
                        },
                        new
                        {
                            ID = 11,
                            Data = new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 3,
                            Number = 22,
                            SaldoInput = 11f,
                            SaldoOutput = 22f,
                            SubAccountID = 3,
                            Sum = 20f,
                            Type = "30"
                        },
                        new
                        {
                            ID = 22,
                            Data = new DateTime(2020, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 4,
                            Number = 15,
                            SaldoInput = 32f,
                            SaldoOutput = 11f,
                            SubAccountID = 4,
                            Sum = 10f,
                            Type = "154"
                        },
                        new
                        {
                            ID = 13,
                            Data = new DateTime(2020, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 5,
                            Number = 5,
                            SaldoInput = 17f,
                            SaldoOutput = 18f,
                            SubAccountID = 5,
                            Sum = 16f,
                            Type = "1643"
                        },
                        new
                        {
                            ID = 200,
                            Data = new DateTime(2020, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 6,
                            Number = 112,
                            SaldoInput = 321f,
                            SaldoOutput = 143f,
                            SubAccountID = 6,
                            Sum = 167f,
                            Type = "1112"
                        },
                        new
                        {
                            ID = 666,
                            Data = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealID = 7,
                            Number = 777,
                            SaldoInput = 666f,
                            SaldoOutput = 777f,
                            SubAccountID = 7,
                            Sum = 777f,
                            Type = "666"
                        });
                });

            modelBuilder.Entity("_3._1.Models.SubAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountPlanID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SubAccount");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AccountPlanID = 1,
                            Name = "1",
                            Number = 2
                        },
                        new
                        {
                            ID = 2,
                            AccountPlanID = 2,
                            Name = "2",
                            Number = 1
                        },
                        new
                        {
                            ID = 3,
                            AccountPlanID = 3,
                            Name = "3",
                            Number = 3
                        },
                        new
                        {
                            ID = 4,
                            AccountPlanID = 4,
                            Name = "4",
                            Number = 4
                        },
                        new
                        {
                            ID = 5,
                            AccountPlanID = 5,
                            Name = "5",
                            Number = 5
                        },
                        new
                        {
                            ID = 6,
                            AccountPlanID = 6,
                            Name = "6",
                            Number = 6
                        },
                        new
                        {
                            ID = 7,
                            AccountPlanID = 7,
                            Name = "7",
                            Number = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
